version: '3'

services:
  qinglong:
    image: whyour/qinglong:latest
    volumes:
      - ./data:/ql/data
    ports:
      - 5700:5700
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped