version: '3'

services:
  samba:
    image: dperson/samba:latest
    container_name: samba
    environment:
      - TZ=Asia/Shanghai
      - PUID=PUID
      - PGID=PGID
    volumes:
      - /media-storage:/share
    ports:
      - 139:139
      - 445:445
    command:
      - '-r'
      - '-s "media-storage;/share"'
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped
  
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=PUID
      - PGID=PGID
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true
    volumes:
      - ./jackett/config:/config
    ports:
      - 9117:9117
    restart: unless-stopped

  jellyfin:
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=PUID
      - PGID=PGID
      - TZ=Asia/Shanghai
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /media-storage/media:/media
    devices:
      - /dev/dri:/dev/dir
    deploy:
      resources:
        limits:
          memory: 2G
    restart: unless-stopped
